import { Demand, Property } from '../models/index.js';
import { Op } from 'sequelize';

/**
 * D2DC (garbage collection) demand generation logic.
 * Used by unified orchestrator to generate separate D2DC demand for a property.
 */

/**
 * Generate D2DC demand for a property.
 * Creates its own separate Demand record (not DemandItem).
 * @returns {{ demand: Demand, created: boolean }}
 */
export const generateD2DCDemandForProperty = async (propertyId, month, assessorId, baseAmount = 50, dueDate = null, remarks = null, transaction = null) => {
  // Check if D2DC demand already exists for this property and month
  const existingDemand = await Demand.findOne({
    where: {
      propertyId,
      serviceType: 'D2DC',
      financialYear: month // Using financialYear field to store month/year for D2DC
    },
    transaction
  });

  if (existingDemand) {
    return { demand: existingDemand, created: false };
  }

  // Calculate arrears from previous unpaid D2DC demands
  const previousDemands = await Demand.findAll({
    where: {
      propertyId,
      serviceType: 'D2DC',
      financialYear: { [Op.ne]: month },
      status: { [Op.in]: ['pending', 'overdue', 'partially_paid'] }
    },
    transaction
  });

  const arrearsAmount = Math.round(previousDemands.reduce((sum, prevDemand) => {
    return sum + parseFloat(prevDemand.balanceAmount || 0);
  }, 0) * 100) / 100;

  const calculatedBaseAmount = parseFloat(baseAmount || 50);
  const totalAmount = Math.round((calculatedBaseAmount + arrearsAmount) * 100) / 100;
  const balanceAmount = Math.round(totalAmount * 100) / 100;

  const demandNumber = `D2DC-${month}-${Date.now()}`;
  const demand = await Demand.create({
    demandNumber,
    propertyId,
    assessmentId: null, // D2DC doesn't require assessment
    waterTaxAssessmentId: null,
    shopTaxAssessmentId: null,
    serviceType: 'D2DC',
    financialYear: month,
    baseAmount: calculatedBaseAmount,
    arrearsAmount,
    penaltyAmount: 0,
    interestAmount: 0,
    totalAmount,
    balanceAmount,
    paidAmount: 0,
    dueDate: dueDate ? new Date(dueDate) : new Date(),
    status: 'pending',
    generatedBy: assessorId,
    remarks: remarks || `Auto-generated by unified orchestrator for ${month}`
  }, { transaction });

  return { demand, created: true };
};
