import { Assessment, Property, Demand } from '../models/index.js';
import { generateAssessmentId } from './uniqueIdService.js';
import { Op } from 'sequelize';

/**
 * Get or create property tax assessment for a property and year.
 * @returns {{ assessment: Assessment, created: boolean }}
 */
export const getOrCreatePropertyAssessment = async (propertyId, assessmentYear, assessorId, defaultTaxRate = 1.5, transaction = null) => {
  const existingAssessment = await Assessment.findOne({
    where: {
      propertyId,
      assessmentYear,
      status: { [Op.in]: ['draft', 'pending', 'approved'] }
    },
    transaction
  });

  if (existingAssessment) {
    return { assessment: existingAssessment, created: false };
  }

  const property = await Property.findByPk(propertyId, { transaction });
  if (!property) {
    throw new Error('Property not found');
  }
  if (property.isActive === false) {
    throw new Error(`Cannot generate property tax assessment for inactive property ${property.propertyNumber || propertyId}. Property must be active to receive assessments.`);
  }

  const assessedValue = parseFloat(property.area || 0) * 1000;
  const taxRate = defaultTaxRate;
  const netAssessedValue = assessedValue;
  const annualTaxAmount = (netAssessedValue * taxRate) / 100;
  const assessmentNumber = await generateAssessmentId(property.wardId, 'property', transaction);

  const assessment = await Assessment.create({
    assessmentNumber,
    propertyId,
    assessmentYear,
    assessedValue,
    taxRate,
    annualTaxAmount,
    assessorId,
    status: 'draft',
    remarks: 'Auto-generated by unified tax service'
  }, { transaction });

  return { assessment, created: true };
};

/**
 * Compute property tax arrears for a property and financial year (HOUSE_TAX).
 */
export const computePropertyArrears = async (propertyId, financialYear, transaction = null) => {
  const previousDemands = await Demand.findAll({
    where: {
      propertyId,
      serviceType: 'HOUSE_TAX',
      financialYear: { [Op.ne]: financialYear },
      status: { [Op.in]: ['pending', 'overdue', 'partially_paid'] }
    },
    transaction
  });
  return Math.round(previousDemands.reduce((sum, prevDemand) => sum + parseFloat(prevDemand.balanceAmount || 0), 0) * 100) / 100;
};

/**
 * Get or create property assessment and compute base + arrears for demand generation.
 * Used by unified orchestrator (no Demand created here).
 * @returns {{ assessment: Assessment | null, baseAmount: number, arrearsAmount: number, created: boolean }}
 */
export const getOrCreateAssessmentAndComputeAmounts = async (propertyId, assessmentYear, financialYear, assessorId, defaultTaxRate = 1.5, transaction = null) => {
  const { assessment, created } = await getOrCreatePropertyAssessment(propertyId, assessmentYear, assessorId, defaultTaxRate, transaction);
  const baseAmount = parseFloat(assessment.annualTaxAmount || 0);
  const arrearsAmount = await computePropertyArrears(propertyId, financialYear, transaction);
  return { assessment, baseAmount, arrearsAmount, created };
};
