export const EMAIL_EVENTS = {
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  DEMAND_GENERATED: 'DEMAND_GENERATED',
};

export const ROLE_EVENT_MAPPING = {
  [EMAIL_EVENTS.PAYMENT_CREATED]: ['admin', 'officer'],
  [EMAIL_EVENTS.PAYMENT_APPROVED]: ['collector'],
  [EMAIL_EVENTS.PAYMENT_SUCCESS]: ['citizen'],
  [EMAIL_EVENTS.DEMAND_GENERATED]: ['citizen'],
};
