ALTER TABLE assessments
ADD COLUMN IF NOT EXISTS "landValue" DECIMAL(12, 2),
ADD COLUMN IF NOT EXISTS "buildingValue" DECIMAL(12, 2),
ADD COLUMN IF NOT EXISTS "depreciation" DECIMAL(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS "exemptionAmount" DECIMAL(12, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS "effectiveDate" DATE,
ADD COLUMN IF NOT EXISTS "expiryDate" DATE,
ADD COLUMN IF NOT EXISTS "revisionNumber" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "previousAssessmentId" INTEGER REFERENCES assessments(id);
