import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { taskAPI } from '../../services/api';
import Loading from '../../components/Loading';
import toast from 'react-hot-toast';
import { CheckCircle, Clock, AlertTriangle, MapPin, User, DollarSign, Calendar, Phone, FileText, ArrowRight } from 'lucide-react';

const DailyTasks = () => {
  const navigate = useNavigate();
  const [tasks, setTasks] = useState([]);
  const [tasksByPriority, setTasksByPriority] = useState({});
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState(null);

  useEffect(() => {
    fetchDailyTasks();
  }, []);

  const fetchDailyTasks = async () => {
    try {
      setLoading(true);
      const response = await taskAPI.getDaily();
      setTasks(response.data.data.tasks);
      setTasksByPriority(response.data.data.tasksByPriority);
      setSummary(response.data.data.summary);
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to fetch daily tasks');
    } finally {
      setLoading(false);
    }
  };

  const handleTaskClick = (task) => {
    setSelectedTask(task);
    // Navigate to field visit recording page with task context
    navigate(`/collector/field-visit/new`, {
      state: {
        taskId: task.id,
        demandId: task.demandId,
        propertyId: task.propertyId,
        ownerId: task.ownerId
      }
    });
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'critical':
        return 'bg-red-100 border-red-300 text-red-800';
      case 'high':
        return 'bg-orange-100 border-orange-300 text-orange-800';
      case 'medium':
        return 'bg-yellow-100 border-yellow-300 text-yellow-800';
      case 'low':
        return 'bg-blue-100 border-blue-300 text-blue-800';
      default:
        return 'bg-gray-100 border-gray-300 text-gray-800';
    }
  };

  const getPriorityBadge = (priority) => {
    switch (priority) {
      case 'critical':
        return <span className="px-2 py-1 text-xs font-bold bg-red-600 text-white rounded">CRITICAL</span>;
      case 'high':
        return <span className="px-2 py-1 text-xs font-bold bg-orange-600 text-white rounded">HIGH</span>;
      case 'medium':
        return <span className="px-2 py-1 text-xs font-bold bg-yellow-600 text-white rounded">MEDIUM</span>;
      case 'low':
        return <span className="px-2 py-1 text-xs font-bold bg-blue-600 text-white rounded">LOW</span>;
      default:
        return null;
    }
  };

  const formatCurrency = (amount) => {
    return `₹${parseFloat(amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  if (loading) return <Loading />;

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Today's Field Tasks</h1>
          <p className="text-gray-600 mt-1">Your assigned tasks for today - Auto-generated by system</p>
        </div>
        <button
          onClick={fetchDailyTasks}
          className="btn btn-secondary"
        >
          Refresh
        </button>
      </div>

      {/* Summary Cards */}
      {summary && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <div className="card bg-red-50 border-red-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-red-600 font-medium">Critical</p>
                <p className="text-2xl font-bold text-red-900">{summary.critical}</p>
              </div>
              <AlertTriangle className="w-8 h-8 text-red-600" />
            </div>
          </div>
          <div className="card bg-orange-50 border-orange-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-orange-600 font-medium">High Priority</p>
                <p className="text-2xl font-bold text-orange-900">{summary.high}</p>
              </div>
              <Clock className="w-8 h-8 text-orange-600" />
            </div>
          </div>
          <div className="card bg-yellow-50 border-yellow-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-yellow-600 font-medium">Medium</p>
                <p className="text-2xl font-bold text-yellow-900">{summary.medium}</p>
              </div>
              <FileText className="w-8 h-8 text-yellow-600" />
            </div>
          </div>
          <div className="card bg-blue-50 border-blue-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-blue-600 font-medium">Total Tasks</p>
                <p className="text-2xl font-bold text-blue-900">{summary.total}</p>
              </div>
              <CheckCircle className="w-8 h-8 text-blue-600" />
            </div>
          </div>
        </div>
      )}

      {/* Tasks by Priority */}
      {tasks.length === 0 ? (
        <div className="card text-center py-12">
          <CheckCircle className="w-16 h-16 text-green-500 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-gray-900 mb-2">No Tasks for Today</h3>
          <p className="text-gray-600">All caught up! No pending field visits required today.</p>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Critical Priority Tasks */}
          {tasksByPriority.critical && tasksByPriority.critical.length > 0 && (
            <div>
              <h2 className="text-xl font-bold text-red-900 mb-4 flex items-center">
                <AlertTriangle className="w-5 h-5 mr-2" />
                Critical Priority ({tasksByPriority.critical.length})
              </h2>
              <div className="space-y-3">
                {tasksByPriority.critical.map((task) => (
                  <TaskCard
                    key={task.id}
                    task={task}
                    onClick={() => handleTaskClick(task)}
                    getPriorityBadge={getPriorityBadge}
                    formatCurrency={formatCurrency}
                  />
                ))}
              </div>
            </div>
          )}

          {/* High Priority Tasks */}
          {tasksByPriority.high && tasksByPriority.high.length > 0 && (
            <div>
              <h2 className="text-xl font-bold text-orange-900 mb-4 flex items-center">
                <Clock className="w-5 h-5 mr-2" />
                High Priority ({tasksByPriority.high.length})
              </h2>
              <div className="space-y-3">
                {tasksByPriority.high.map((task) => (
                  <TaskCard
                    key={task.id}
                    task={task}
                    onClick={() => handleTaskClick(task)}
                    getPriorityBadge={getPriorityBadge}
                    formatCurrency={formatCurrency}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Medium Priority Tasks */}
          {tasksByPriority.medium && tasksByPriority.medium.length > 0 && (
            <div>
              <h2 className="text-xl font-bold text-yellow-900 mb-4 flex items-center">
                <FileText className="w-5 h-5 mr-2" />
                Medium Priority ({tasksByPriority.medium.length})
              </h2>
              <div className="space-y-3">
                {tasksByPriority.medium.map((task) => (
                  <TaskCard
                    key={task.id}
                    task={task}
                    onClick={() => handleTaskClick(task)}
                    getPriorityBadge={getPriorityBadge}
                    formatCurrency={formatCurrency}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Low Priority Tasks */}
          {tasksByPriority.low && tasksByPriority.low.length > 0 && (
            <div>
              <h2 className="text-xl font-bold text-blue-900 mb-4 flex items-center">
                <CheckCircle className="w-5 h-5 mr-2" />
                Low Priority ({tasksByPriority.low.length})
              </h2>
              <div className="space-y-3">
                {tasksByPriority.low.map((task) => (
                  <TaskCard
                    key={task.id}
                    task={task}
                    onClick={() => handleTaskClick(task)}
                    getPriorityBadge={getPriorityBadge}
                    formatCurrency={formatCurrency}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// Task Card Component
const TaskCard = ({ task, onClick, getPriorityBadge, formatCurrency }) => {
  // Get serviceType from demand if available
  const serviceType = task.demand?.serviceType || 'HOUSE_TAX';
  const isD2DC = serviceType === 'D2DC';
  
  const getServiceTypeBadge = () => {
    if (isD2DC) {
      return (
        <span className="px-2 py-1 text-xs font-semibold bg-green-100 text-green-800 rounded border border-green-300">
          D2DC
        </span>
      );
    }
    return (
      <span className="px-2 py-1 text-xs font-semibold bg-blue-100 text-blue-800 rounded border border-blue-300">
        House Tax
      </span>
    );
  };

  return (
    <div
      className="card hover:shadow-lg transition-all cursor-pointer border-l-4"
      style={{
        borderLeftColor: task.priority === 'critical' ? '#dc2626' : 
                         task.priority === 'high' ? '#ea580c' :
                         task.priority === 'medium' ? '#ca8a04' : '#2563eb'
      }}
      onClick={onClick}
    >
      <div className="flex justify-between items-start mb-4">
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-2 flex-wrap">
            {getPriorityBadge(task.priority)}
            {getServiceTypeBadge()}
            <span className="text-xs text-gray-500">Task #{task.taskNumber}</span>
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">{task.actionRequired}</h3>
        </div>
        <ArrowRight className="w-5 h-5 text-gray-400" />
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
        <div className="flex items-center">
          <User className="w-4 h-4 mr-2 text-gray-400" />
          <div>
            <p className="text-xs text-gray-500">Citizen</p>
            <p className="text-sm font-medium">{task.citizenName}</p>
          </div>
        </div>
        <div className="flex items-center">
          <MapPin className="w-4 h-4 mr-2 text-gray-400" />
          <div>
            <p className="text-xs text-gray-500">Property</p>
            <p className="text-sm font-medium">{task.propertyNumber}</p>
          </div>
        </div>
        <div className="flex items-center">
          <DollarSign className="w-4 h-4 mr-2 text-gray-400" />
          <div>
            <p className="text-xs text-gray-500">Amount Due</p>
            <p className="text-sm font-medium text-red-600">{formatCurrency(task.dueAmount)}</p>
          </div>
        </div>
        <div className="flex items-center">
          <Calendar className="w-4 h-4 mr-2 text-gray-400" />
          <div>
            <p className="text-xs text-gray-500">Overdue</p>
            <p className="text-sm font-medium">{task.overdueDays} days</p>
          </div>
        </div>
      </div>

      {task.lastVisitDate && (
        <div className="flex items-center text-sm text-gray-600 mb-2">
          <Clock className="w-4 h-4 mr-2" />
          <span>Last visit: {new Date(task.lastVisitDate).toLocaleDateString()} ({task.visitCount} visits)</span>
        </div>
      )}

      {task.expectedPaymentDate && (
        <div className="flex items-center text-sm text-orange-600 mb-2">
          <Calendar className="w-4 h-4 mr-2" />
          <span>Expected payment: {new Date(task.expectedPaymentDate).toLocaleDateString()}</span>
        </div>
      )}

      <div className="mt-4 pt-4 border-t border-gray-200">
        <button className="btn btn-primary w-full">
          Record Field Visit
        </button>
      </div>
    </div>
  );
};

export default DailyTasks;
