import { DataTypes } from 'sequelize';
import { sequelize } from '../config/database.js';

export const CollectorTask = sequelize.define('CollectorTask', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  taskNumber: {
    type: DataTypes.STRING(50),
    allowNull: false,
    unique: true,
    comment: 'Auto-generated unique task number'
  },
  collectorId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Users',
      key: 'id'
    },
    comment: 'Collector assigned to this task'
  },
  demandId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Demands',
      key: 'id'
    },
    comment: 'Demand for which task is generated'
  },
  propertyId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Properties',
      key: 'id'
    }
  },
  ownerId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Users',
      key: 'id'
    }
  },
  followUpId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'follow_ups',
      key: 'id'
    },
    comment: 'Related follow-up record'
  },
  taskDate: {
    type: DataTypes.DATEONLY,
    allowNull: false,
    comment: 'Date for which task is assigned (usually today)'
  },
  taskType: {
    type: DataTypes.ENUM('overdue_followup', 'promised_payment', 'escalation_visit', 'enforcement_visit', 'due_today'),
    allowNull: false,
    comment: 'Type of task'
  },
  priority: {
    type: DataTypes.ENUM('low', 'medium', 'high', 'critical'),
    allowNull: false,
    defaultValue: 'medium',
    comment: 'Task priority level'
  },
  actionRequired: {
    type: DataTypes.TEXT,
    allowNull: false,
    comment: 'Description of action required'
  },
  // Context information
  citizenName: {
    type: DataTypes.STRING(200),
    allowNull: false,
    comment: 'Citizen name (denormalized for quick display)'
  },
  propertyNumber: {
    type: DataTypes.STRING(50),
    allowNull: false,
    comment: 'Property number (denormalized)'
  },
  wardNumber: {
    type: DataTypes.STRING(20),
    allowNull: true,
    comment: 'Ward number (denormalized)'
  },
  dueAmount: {
    type: DataTypes.DECIMAL(12, 2),
    allowNull: false,
    comment: 'Amount due (denormalized)'
  },
  overdueDays: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    comment: 'Days overdue (denormalized)'
  },
  visitCount: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
    comment: 'Number of visits made (denormalized)'
  },
  lastVisitDate: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Last visit date (denormalized)'
  },
  lastVisitStatus: {
    type: DataTypes.STRING(100),
    allowNull: true,
    comment: 'Last visit status (denormalized)'
  },
  expectedPaymentDate: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Expected payment date from last visit'
  },
  // Task status
  status: {
    type: DataTypes.ENUM('pending', 'in_progress', 'completed', 'cancelled', 'expired'),
    defaultValue: 'pending',
    comment: 'Task status'
  },
  completedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'When task was completed'
  },
  completedBy: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'Users',
      key: 'id'
    },
    comment: 'Collector who completed the task'
  },
  completionNote: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Note when task was completed'
  },
  relatedVisitId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'field_visits',
      key: 'id'
    },
    comment: 'Field visit created when task was completed'
  },
  // Generation metadata
  generatedBy: {
    type: DataTypes.ENUM('system', 'admin'),
    allowNull: false,
    defaultValue: 'system',
    comment: 'Who/what generated this task'
  },
  generationReason: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Reason why task was generated'
  },
  isAutoGenerated: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: true,
    comment: 'Whether task was auto-generated by system'
  }
}, {
  tableName: 'collector_tasks',
  timestamps: true,
  indexes: [
    {
      unique: true,
      fields: ['taskNumber']
    },
    {
      fields: ['collectorId', 'taskDate']
    },
    {
      fields: ['demandId']
    },
    {
      fields: ['status']
    },
    {
      fields: ['priority']
    },
    {
      fields: ['taskType']
    },
    {
      fields: ['taskDate', 'status']
    }
  ],
  hooks: {
    beforeCreate: async (task) => {
      // Auto-generate task number if not provided (fallback)
      // Format: TASK-YYYYMMDD-{collectorId}-{sequence}
      if (!task.taskNumber) {
        const taskDate = task.taskDate || new Date().toISOString().split('T')[0];
        const dateFormatted = taskDate.replace(/-/g, ''); // YYYYMMDD format
        const collectorId = task.collectorId || 0;
        
        // Count existing tasks for this collector on this date
        const count = await CollectorTask.count({
          where: {
            collectorId: collectorId,
            taskDate: taskDate
          }
        });
        
        const sequence = String(count + 1).padStart(3, '0'); // 001, 002, etc.
        task.taskNumber = `TASK-${dateFormatted}-${collectorId}-${sequence}`;
      }
    }
  }
});
